### ISSUE TITLE
Module not found after installation

### ISSUE THREAD

**Issue by jhwilmot** [kpuhger/fiberphotopy#3]
Yusuke and I pip installed and both got the following error when trying to import the package in a notebook.

ModuleNotFoundError: No module named 'fiberphotopy'

**Comment by kpeez** [comment]
I just updated the package on PyPi should now it should work with `pip install fiberphotopy` instead of the repo URL. Can you give that a try and let me know if that works?

**Comment by jhwilmot** [comment]
When I install it I end up with 3 folders: fiberphotopy-0.0.2.dist-info, preprocess, and plotting. I can import the preprocess or plotting so seems like you just need to do something so that those end up installed inside of a folder called fiberphotopy instead of as their own separate folders
<img width="700" alt="Screen Shot 2022-03-07 at 3 40 49 PM" src="https://user-images.githubusercontent.com/27505931/157136855-8ad33359-d477-47fe-b5ce-a5fb6dcc703e.png">
.

**Comment by kpeez** [comment]
Hm alright, I will have to look into why it's not packaging correctly. In the meantime you can clone the repo and use `sys.path` in your notebook like the old package.

**Comment by kpeez** [comment]
I still haven't been able to figure out why the package isn't being distributed properly, but have added updated installation instructions to the README with a workaround.

**Comment by kpeez** [comment]
Okay, I restructured the package and I _think_ the install directly from pip should work now. Let me know if it does when you have a chance to try it out.
